### ISSUE TITLE
Unable to select model: "API key is not valid"

### ISSUE THREAD

**Issue by quinn-p-mchugh** [chuanqixu/anki-quick-ai#3]
Hi there,

Thanks for taking the time to develop this! 

I'd like to try it out, but after entering my OpenAI API Key via the add-on config, I can't seem to select a model - the add-on continually indicates "API key is not valid" and does not provide a dropdown to select a model. I've recreated the API key via https://platform.openai.com/api-keys, so I'm fairly confident I'm using a valid API key. Screenshot provided below::

<img width="154" alt="image" src="https://github.com/chuanqixu/anki-quick-ai/assets/40648753/5de9244a-a2cd-4ef7-96de-b8c1f4aeadf7">

In addition, trying to use the prompt interface yields the following error:

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\controller.py", line 66, in run
    self.initial_response()
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\controller.py", line 92, in initial_response
    self.response(prompt)
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\controller.py", line 76, in response
    response = call_openai(self.model, prompt, self.system_prompt, **self.ai_config)
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\ai.py", line 15, in call_openai
    completion = openai.ChatCompletion.create(
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\lib\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\lib\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\qpmch\AppData\Roaming\Anki2\addons21\547821970\lib\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: invalid model ID

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['readwise-anki-gpt', 0, 'None', '']
Anki Quick AI ['547821970', 2023-11-29T22:37, 'None', mod]

===IDs of active AnkiWeb add-ons===
547821970

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by quinn-p-mchugh** [comment]
Just tested the API key I was using above against the latest version of the OpenAI API

The following code is successful.

Given this, it seems there might have been a major change in the API since this add-on was developed?

```
from openai import OpenAI
client = OpenAI(api_key='<My API Key>')

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)

print(completion.choices[0].message)

**Comment by chuanqixu** [comment]
Hi @quinn-p-mchugh, thank you very much for pointing out this issue!

I changed the previous hardcoded models to retrieve the available models based on the provided API key.
However, it is strange to me because I thought the previous hardcoded models should still be available to users, such as `gpt-3.5-turbo` you used for testing.

I am not confident whether this is solved, so I would appreciate you updating to the latest version and having a try.
If it is not solved, could you please share with me your Anki version to double-check, and I would be grateful if you could send me your key over email if you don't mind.

Thanks again!

**Comment by quinn-p-mchugh** [comment]
Hi @chuanqixu,

Thanks for taking a look!

Strange indeed. [`gpt-3.5-turbo` still points to the latest model](https://platform.openai.com/docs/models/continuous-model-upgrades#:~:text=gpt%2D3.5%2Dturbo%2C%20gpt%2D4%2C%20and%20gpt%2D4%2D32k%20point%20to%20the%20latest%20model%20version.%20You%20can%20verify%20this%20by%20looking%20at%20the%20response%20object%20after%20sending%20a%20request.%20The%20response%20will%20include%20the%20specific%20model%20version%20used%20(e.g.%20gpt%2D3.5%2Dturbo%2D0613).), so no issues there.

After perusing through [`gpt.py`](https://github.com/chuanqixu/anki-quick-ai/blob/1873fd08533fb82cb4bcab5801f9ce0de04f7322/src/gpt.py#L34C9-L34C9), it seems like this add-on uses an older version of the [openai python library](https://github.com/openai/openai-python). The syntax of the latest version is significantly different, which might be related to the issue at hand.

**Comment by chuanqixu** [comment]
I am sorry that I could not find a good way to debug since this problem does not appear on my side.

## Code

This problem should be that the model list cannot be retrieved.
More specifically, it is the function `get_avail_chat_model_lis` in [add-on/ai.py](https://github.com/chuanqixu/anki-quick-ai/blob/main/add-on/ai.py).
It only contains several lines of code and should be easy to debug.

## Check

I would suggest checking whether you input the correct key, though I think you should have done this many times.
Please also check with the code:
``` python
import openai

client = openai.OpenAI(api_key='<My API Key>')

models = client.models.list().data
print(models)

avail_chat_model_list = [model.id for model in models if model.id.startswith("gpt")]
print("avail_chat_model_list")
print(avail_chat_model_list)
```
If `avail_chat_model_list` is empty, it will show "API key is not valid" because I assume that a valid API key should contain at least one gpt model.

## Compatibility with Newer Version of OpenAI Library

Because libraries for Anki add-ons will be attached with them when publicizing, which means the openai library used for this add-on is the old version, there should not be compatibility issue since I am using it with no problems, so it seems that the old version is still supported and usable.

That being said, I still updated to the latest version of openai in the new add-on version.
I appreciate your effort in updating and testing, and I hope that it will solve the issues.

If the problem still exists, I would be grateful if you could share your key.
If you are using it in many places and it is not convenient, you may create a new key and share it with me.
I will only use it for testing and you could delete it when it is solved.

**Comment by quinn-p-mchugh** [comment]
Hi @chuanqixu,

Thanks for taking the time to update the `openai` library to the latest version.

**I've updated the add-on to the latest version and am happy to report the add-on now works properly!**

I can now select my desired model via the config and receive messages from ChatGPT as expected. I did not have to update my API key.

Based on this, is it possible the difference between the **age** of your API key and my API key is the source of the issue?

In any case, please feel free to close this issue. Thank you for being so generous with your time and support.

**Comment by chuanqixu** [comment]
Thank you for posting and testing this issue!

I guess that API keys are assigned with API versions so that they may not be back-compatible, though I tried to search and there seems to be no information about this.
